// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhRqPfeeY07rWTfwZls5H3i7UxhyBydQs',
    appId: '1:226261201491:web:a29c34640c66ce28720ca6',
    messagingSenderId: '226261201491',
    projectId: 'health-app-5bb3b',
    authDomain: 'health-app-5bb3b.firebaseapp.com',
    storageBucket: 'health-app-5bb3b.firebasestorage.app',
    measurementId: 'G-QXL4CTSQVH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyRpcrO7_ZWECBOqjjdV1CBf720l3JTVo',
    appId: '1:226261201491:android:f576f7008afaf82e720ca6',
    messagingSenderId: '226261201491',
    projectId: 'health-app-5bb3b',
    storageBucket: 'health-app-5bb3b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCArcHgAPL7I6_JwTUmJ9KbZCsLNW-3O-A',
    appId: '1:226261201491:ios:dbee838521222df4720ca6',
    messagingSenderId: '226261201491',
    projectId: 'health-app-5bb3b',
    storageBucket: 'health-app-5bb3b.firebasestorage.app',
    iosBundleId: 'com.example.health',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCArcHgAPL7I6_JwTUmJ9KbZCsLNW-3O-A',
    appId: '1:226261201491:ios:dbee838521222df4720ca6',
    messagingSenderId: '226261201491',
    projectId: 'health-app-5bb3b',
    storageBucket: 'health-app-5bb3b.firebasestorage.app',
    iosBundleId: 'com.example.health',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhRqPfeeY07rWTfwZls5H3i7UxhyBydQs',
    appId: '1:226261201491:web:0f0c11bf2e0ecf5a720ca6',
    messagingSenderId: '226261201491',
    projectId: 'health-app-5bb3b',
    authDomain: 'health-app-5bb3b.firebaseapp.com',
    storageBucket: 'health-app-5bb3b.firebasestorage.app',
    measurementId: 'G-L8Z1MWC6J9',
  );
}
